# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apk',
            name='md5',
        ),
        migrations.AddField(
            model_name='apk',
            name='sha1',
            field=models.CharField(db_index=True, default='', max_length=40),
            preserve_default=False,
        ),
    ]
